server:
  port: 8081
  servlet:
    context-path: /e-test

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cdb-fnp352jy.cd.tencentcdb.com:10029/e-commerceweb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 373d784e7f7c
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true





